is_repertoire: True
path: ./
paired: False
import_illegal_characters: False
region_type: "IMGT_CDR3" # which region to use - IMGT_CDR3 option means removing first and last amino acid as AIRR uses IMGT junction as CDR3
separator: "\t"
import_empty_nt_sequences: True # keep sequences even though the nucleotide sequence might be empty
import_empty_aa_sequences: False # filter out sequences if they don't have sequence_aa set