is_repertoire: True
path: ./
paired: False
import_productive: True
import_with_stop_codon: False
import_out_of_frame: False
import_illegal_characters: False
region_type: "IMGT_CDR3" # which region to on import
separator: "\t"
columns_to_load: [nucleotide, aminoAcid, count (templates/reads), vGeneName, jGeneName, sequenceStatus] # columns from the original file that will be imported
column_mapping: # immunoSEQ column names -> immuneML repertoire fields
  nucleotide: sequence # nucleotide is the immunoSEQ name, which will be mapped to sequence in immuneML
  aminoAcid: junction_aa
  vGeneName: v_call
  jGeneName: j_call
  sequenceStatus: frame_type
  count (templates/reads): duplicate_count
import_empty_nt_sequences: True # keep sequences even though the nucleotide sequence might be empty
import_empty_aa_sequences: False # filter out sequences if they don't have sequence_aa set
organism: human
label_columns: null