is_repertoire: True
path: ./
import_productive: True # whether to only import productive sequences
import_unproductive: False # whether to only import unproductive sequences
import_unknown_productivity: True # whether to import sequences with unknown productivity (missing/NA)
import_illegal_characters: False
region_type: "IMGT_CDR3" # which region to use - IMGT_CDR3 option means removing first and last amino acid as 10xGenomics uses IMGT junction as CDR3
separator: "\t" # column separator
column_mapping: # 10xGenomics column names -> immuneML repertoire fields
  cdr3: junction_aa
  cdr3_nt: junction
  chain: locus
  v_gene: v_call
  d_gene: d_call
  j_gene: j_call
  c_gene: c_call
  umis: umi_count
  reads: consensus_count
  productive: productive
  barcode: cell_id
  raw_clonotype_id: clone_id
  raw_consensus_id: sequence_id
import_empty_nt_sequences: True # keep sequences even though the nucleotide sequence might be empty
import_empty_aa_sequences: False # filter out sequences if they don't have sequence_aa set