validation_part: 0.2 # the part of the data that will be used for validation, the rest will be used for training
add_positional_information: True
kernel_size: 9
n_kernels: 32
n_additional_convs: 0
n_attention_network_layers: 2
n_attention_network_units: 32
n_output_network_units: 32
consider_seq_counts: False
sequence_reduction_fraction: 0.1
reduction_mb_size: 50000
n_updates: 100000
evaluate_at: 5000
n_torch_threads: 3
learning_rate: 0.0001
l1_weight_decay: 0
l2_weight_decay: 0
sample_n_sequences: 10000
training_batch_size: 4 # Number of repertoires per minibatch during training.
n_workers: 4
pytorch_device_name: cuda:0
keep_dataset_in_ram: True