kernel_count: 2
kernel_size: [3, 4]
positional_channels: 3
sequence_type: amino_acid
device: cpu
number_of_threads: 16
random_seed: 100
learning_rate: 0.01
iteration_count: 10000
l1_weight_decay: 0
l2_weight_decay: 0
batch_size: 5000
background_probabilities: null
training_percentage: 0.8
evaluate_at: 5000