locus: null
region_type: IMGT_JUNCTION
hidden_size: 64
num_layers: 3
dropout: 0.
num_epochs: 20
batch_size: 1000
learning_rate: 0.0001
max_length: 30
vj: False
require_c_start: True
aa_embedding_path: null
train_aa_embeddings: False
embed_size: 32
word2vec_epochs: 20
word2vec_batch_size: 1000
word2vec_learning_rate: 0.0001
word2vec_window_size: 2
device: cpu
seed: null
