is_repertoire: True
paired: False
import_productive: True
import_with_stop_codon: False
import_out_of_frame: False
batch_size: 4
region_type: "IMGT_CDR3" # which region to use - IMGT_CDR3 option means removing first and last amino acid as AIRR uses IMGT junction as CDR3
separator: "\t"
columns_to_load: [sequence_aa, sequence, v_call, j_call, locus, duplicate_count, productive, vj_in_frame, stop_codon]
column_mapping: # AIRR column names -> immuneML repertoire fields
  junction: sequences
  junction_aa: sequence_aas
  v_call: v_genes
  j_call: j_genes
  locus: chains
  duplicate_count: counts
  sequence_id: sequence_identifiers