import logging
import shutil
from pathlib import Path

import numpy as np
import pandas as pd

from immuneML.data_model.SequenceParams import RegionType
from immuneML.data_model.bnp_util import write_yaml, read_yaml, get_sequence_field_name
from immuneML.data_model.datasets.ElementDataset import SequenceDataset
from immuneML.environment.EnvironmentSettings import EnvironmentSettings
from immuneML.environment.SequenceType import SequenceType
from immuneML.ml_methods.generative_models.GenerativeModel import GenerativeModel
from immuneML.ml_methods.pytorch_implementations.SimpleLSTMGenerator import SimpleLSTMGenerator
from immuneML.ml_methods.util.pytorch_util import store_weights
from immuneML.util.Logger import print_log
from immuneML.util.PathBuilder import PathBuilder


class SakaLSTM(GenerativeModel):
    """
    A generative model for receptor sequences based on LSTM, where each sequence is modeled separately.

    It is based on Saka et al. (2021), which trains on individual sequences of fixed length rather than on a single
    concatenated stream, and which encodes the input as one-hot vectors rather than learned embeddings:

    Saka, K. et al. (2021). Antibody design using LSTM based deep generative model from phage display library for affinity maturation. Scientific Reports, 11(1), Article 1. https://doi.org/10.1038/s41598-021-85274-7

    Since the original model assumes that all sequences have the same length, a separate LSTM is estimated for each
    sequence length in the dataset, as done for :ref:`PWM`. When generating, a length is first sampled from the length
    distribution of the training data, and the sequence is then generated by the model for that length.

    See :ref:`SimpleLSTM` for a model trained on all sequences concatenated into one character stream.

    **Specification arguments:**

    - sequence_type (str): only amino_acid is supported

    - hidden_size (int): how many LSTM cells should exist per layer

    - num_layers (int): how many hidden LSTM layers should there be

    - dropout (float): dropout rate between LSTM layers; only has an effect if num_layers is larger than 1

    - num_epochs (int): for how many epochs to train each per-length model

    - learning_rate (float): what learning rate to use for optimization

    - batch_size (int): how many sequences to use for training for one batch

    - max_batch_size (int): upper bound on how many sequences of the same length are generated or scored in one
      batch; it does not change the result, only how much is done at once when generating or scoring large numbers
      of sequences

    - temperature (float): controls sampling when generating sequences, with no effect on training; below 1 makes
      generation more conservative, above 1 more diverse

    - seed (int): random seed for the model or None

    - iter_to_report (int): number of epochs between training progress reports


    **YAML specification:**

    .. indent with spaces
    .. code-block:: yaml

        definitions:
            ml_methods:
                my_saka_lstm:
                    sequence_type: amino_acid
                    hidden_size: 64
                    num_layers: 2
                    dropout: 0.2
                    num_epochs: 500
                    learning_rate: 0.01
                    batch_size: 64
                    max_batch_size: 10000

    """

    START_TOKEN = "^"

    @classmethod
    def load_model(cls, path: Path):
        assert path.exists(), f"{cls.__name__}: {path} does not exist."

        model_overview_file = path / 'model_overview.yaml'
        length_probs_file = path / 'length_probabilities.yaml'

        for file in [model_overview_file, length_probs_file]:
            assert file.exists(), f"{cls.__name__}: {file} is not a file."

        model_overview = read_yaml(model_overview_file)
        model = SakaLSTM(**{k: v for k, v in model_overview.items() if k != 'type'})

        model.length_probs = {int(length): float(prob) for length, prob in read_yaml(length_probs_file).items()}
        model._models = {}

        for length in model.length_probs:
            state_dict_file = path / f'state_dict_len_{length}.yaml'
            assert state_dict_file.exists(), f"{cls.__name__}: {state_dict_file} is not a file."
            model._models[length] = model.make_new_model(state_dict_file)

        return model

    def __init__(self, locus: str, sequence_type: str, hidden_size: int, learning_rate: float, num_epochs: int,
                 batch_size: int, num_layers: int, temperature, device: str, dropout: float = 0.2,
                 max_batch_size: int = 10000,
                 name=None, region_type: str = RegionType.IMGT_CDR3.name, seed: int = None,
                 iter_to_report: int = 100):

        super().__init__(locus, region_type=RegionType.get_object(region_type), name=name, seed=seed)
        self.sequence_type = SequenceType[sequence_type.upper()] if sequence_type else SequenceType.AMINO_ACID

        assert self.sequence_type == SequenceType.AMINO_ACID, \
            (f"{SakaLSTM.__name__}: only {SequenceType.AMINO_ACID.name.lower()} is supported, got "
             f"{self.sequence_type.name.lower()}.")

        self.hidden_size = hidden_size
        self.learning_rate = learning_rate
        self.num_layers = num_layers
        self.num_epochs = num_epochs
        self.batch_size = batch_size
        self.dropout = dropout
        self.max_batch_size = max_batch_size
        self.temperature = temperature
        self.device = device
        self.iter_to_report = iter_to_report

        # one LSTM per sequence length, and the length distribution used to pick between them when generating
        self._models = None
        self.length_probs = None

        # no padding or end-of-sequence token is needed: every model works on a single fixed length
        self.unique_letters = EnvironmentSettings.get_sequence_alphabet(self.sequence_type) + [SakaLSTM.START_TOKEN]
        self.num_letters = len(self.unique_letters)
        self.letter_to_index = {letter: i for i, letter in enumerate(self.unique_letters)}
        self.index_to_letter = {i: letter for letter, i in self.letter_to_index.items()}
        self.start_index = self.letter_to_index[SakaLSTM.START_TOKEN]
        self.loss_summary_path = None

    def make_new_model(self, state_dict_file: Path = None):
        from torch import as_tensor

        model = SimpleLSTMGenerator(input_size=self.num_letters, hidden_size=self.hidden_size,
                                    embed_size=None, output_size=self.num_letters,
                                    batch_size=self.batch_size, num_layers=self.num_layers,
                                    device=self.device, dropout=self.dropout)

        if isinstance(state_dict_file, Path) and state_dict_file.is_file():
            state_dict = read_yaml(state_dict_file)
            state_dict = {k: as_tensor(v, device=self.device) for k, v in state_dict.items()}
            model.load_state_dict(state_dict)

        model.to(self.device)
        return model

    def fit(self, data, path: Path = None):
        import torch

        self.set_locus(data)

        if self.seed is not None:
            torch.manual_seed(self.seed)

        sequences = data.get_attribute(get_sequence_field_name(self.region_type, self.sequence_type)).tolist()
        seqs_per_length = {}
        for seq in sequences:
            seqs_per_length.setdefault(len(seq), []).append(seq)

        assert len(seqs_per_length) > 0, f"{SakaLSTM.__name__}: the training dataset is empty."

        total = sum(len(seqs) for seqs in seqs_per_length.values())
        self.length_probs = {length: len(seqs) / total for length, seqs in sorted(seqs_per_length.items())}
        self._models = {}
        loss_summary = {"length": [], "epoch": [], "loss": []}

        for length, seqs_of_length in sorted(seqs_per_length.items()):
            print_log(f"{SakaLSTM.__name__} {self.name}: fitting length {length} ({len(seqs_of_length)} sequences)",
                      True)
            self._models[length] = self._fit_one_length(seqs_of_length, length, loss_summary)

        self._log_training_summary(loss_summary, path)

    def _fit_one_length(self, sequences, length: int, loss_summary):
        """Trains a single LSTM on all training sequences of the given length."""
        import torch
        from torch import nn, optim

        data_loader = self._encode_sequences(sequences)
        model = self.make_new_model()
        model.train()

        criterion = nn.CrossEntropyLoss(reduction='mean')
        optimizer = optim.Adam(model.parameters(), self.learning_rate)

        for epoch in range(self.num_epochs):
            epoch_loss, num_batches = 0., 0

            for x_batch, y_batch in data_loader:
                x_batch, y_batch = x_batch.to(self.device), y_batch.to(self.device)

                state = model.init_zero_state(x_batch.size(0))
                optimizer.zero_grad()

                outputs, _ = model(x_batch, state)
                loss = criterion(outputs.reshape(-1, outputs.size(-1)), y_batch.reshape(-1))

                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5)
                optimizer.step()

                epoch_loss += loss.item()
                num_batches += 1

            self._log_training_progress(loss_summary, length, epoch, epoch_loss / num_batches)

        return model

    def _encode_sequences(self, sequences):
        """Builds one training example per sequence: [START, s_0, ..., s_n-1], with the target shifted by one.
        All sequences here have the same length, so no padding is involved."""
        from torch import as_tensor
        from torch.utils.data import DataLoader, TensorDataset

        encoded = as_tensor([[self.start_index] + [self.letter_to_index[letter] for letter in seq]
                             for seq in sequences]).long()

        x, y = encoded[:, :-1], encoded[:, 1:]

        return DataLoader(TensorDataset(x, y), shuffle=True, batch_size=self.batch_size)

    def generate_sequences(self, count: int, seed: int, path: Path, sequence_type: SequenceType, compute_p_gen: bool):
        import torch

        assert self._models is not None, f"{SakaLSTM.__name__}: the model has not been fitted yet."
        assert sequence_type == self.sequence_type, \
            f"{SakaLSTM.__name__}: expected {self.sequence_type.name}, got {sequence_type.name}."

        torch.manual_seed(seed)
        np.random.seed(seed)

        # all lengths are sampled up front so that the sequences sharing a length can be generated in one batch,
        # which is what makes generating a large number of sequences tractable
        sampled_lengths = np.random.choice(list(self.length_probs.keys()), size=count,
                                           p=list(self.length_probs.values()))

        sequences = [None] * count

        with torch.no_grad():
            for length, indices in self._group_indices_by_length(sampled_lengths).items():
                for chunk in self._chunks(indices):
                    # scatter back to the sampled order, so that the output is not grouped by length
                    for index, seq in zip(chunk, self._generate_batch(length, len(chunk))):
                        sequences[index] = seq

        print_log(f"{SakaLSTM.__name__} {self.name}: generated {len(sequences)} sequences.", True)
        return self._export_dataset(sequences, path)

    def _generate_batch(self, length: int, count: int) -> list:
        """Generates count sequences of exactly the given length at once, all starting from the start token."""
        import torch

        model = self._models[length]
        model.eval()

        state = model.init_zero_state(batch_size=count)
        inp = torch.full((count, 1), self.start_index, device=self.device, dtype=torch.long)
        tokens = torch.empty((count, length), dtype=torch.long)

        for position in range(length):
            output, state = model(inp, state)

            scaled = torch.clamp(output[:, 0] / self.temperature, min=-100, max=100)
            # the start token is only ever an input, so it must not be sampled as part of a sequence
            scaled[:, self.start_index] = -float('inf')

            inp = torch.multinomial(torch.nn.functional.softmax(scaled, dim=1), 1)
            tokens[:, position] = inp[:, 0].cpu()

        letters = np.array(self.unique_letters)
        return ["".join(letters[row]) for row in tokens.numpy()]

    def compute_p_gens(self, sequences, sequence_type: SequenceType, sequence_field: str = None) -> np.ndarray:
        """Generation probability per sequence: the probability of sampling its length, times the autoregressive
        probability of its characters under the model for that length. Saka et al. rank candidates by the negative
        log of the second term. Sequences of a length that was not seen in training get a probability of 0."""
        import torch

        assert sequence_type == self.sequence_type, \
            f"{SakaLSTM.__name__}: expected {self.sequence_type}, got {sequence_type}."
        assert self._models is not None, f"{SakaLSTM.__name__}: the model has not been fitted yet."

        seqs = self._extract_sequence_strings(sequences, sequence_type, sequence_field)
        p_gens = np.zeros(len(seqs))

        with torch.no_grad():
            for length, indices in self._group_indices_by_length([len(seq) for seq in seqs]).items():
                if length not in self._models or length == 0:
                    continue

                for chunk in self._chunks(indices):
                    p_gens[chunk] = self._score_batch(length, [seqs[index] for index in chunk])

        return p_gens

    def compute_p_gen(self, sequence: dict, sequence_type: SequenceType) -> float:
        return float(self.compute_p_gens([sequence], sequence_type)[0])

    def _score_batch(self, length: int, seqs: list) -> np.ndarray:
        import torch

        model = self._models[length]
        model.eval()

        try:
            encoded = torch.as_tensor([[self.start_index] + [self.letter_to_index[letter] for letter in seq]
                                       for seq in seqs], device=self.device).long()
        except KeyError as e:
            raise KeyError(f"{SakaLSTM.__name__}: cannot compute the generation probability of a sequence containing "
                           f"{e}, which is not in the alphabet for {self.sequence_type.name}.")

        x, y = encoded[:, :-1], encoded[:, 1:]

        outputs, _ = model(x, model.init_zero_state(batch_size=len(seqs)))
        log_probs = torch.nn.functional.log_softmax(outputs, dim=-1)
        log_p_seqs = log_probs.gather(2, y.unsqueeze(-1)).squeeze(-1).sum(dim=1)

        return self.length_probs[length] * np.exp(log_p_seqs.detach().cpu().numpy())

    def _extract_sequence_strings(self, sequences, sequence_type: SequenceType, sequence_field: str = None) -> list:
        """Accepts the sequence container used by the simulation instructions, a list of dicts, or a list of
        strings, and returns plain strings."""
        field = sequence_field if sequence_field is not None \
            else get_sequence_field_name(self.region_type, sequence_type)

        def to_str(value):
            return value.to_string() if hasattr(value, 'to_string') else str(value)

        if hasattr(sequences, field):
            return [to_str(value) for value in getattr(sequences, field)]

        return [to_str(seq[field] if field in seq else seq['sequence']) if isinstance(seq, dict) else to_str(seq)
                for seq in sequences]

    @staticmethod
    def _group_indices_by_length(lengths) -> dict:
        groups = {}
        for index, length in enumerate(lengths):
            groups.setdefault(int(length), []).append(index)
        return groups

    def _chunks(self, indices: list):
        """Splits the indices for one length into batches, so that generating or scoring a very large number of
        sequences does not build one enormous batch."""
        for start in range(0, len(indices), self.max_batch_size):
            yield indices[start:start + self.max_batch_size]

    def can_compute_p_gens(self) -> bool:
        return True

    def can_generate_from_skewed_gene_models(self) -> bool:
        return False

    def generate_from_skewed_gene_models(self, v_genes: list, j_genes: list, seed: int, path: Path,
                                         sequence_type: SequenceType, batch_size: int, compute_p_gen: bool):
        raise RuntimeError

    def is_same(self, model) -> bool:
        raise NotImplementedError

    def _log_training_progress(self, loss_summary, length, epoch, loss):
        if (epoch + 1) % self.iter_to_report == 0:
            print_log(f"{SakaLSTM.__name__}: length {length}, epoch [{epoch + 1}/{self.num_epochs}]: "
                      f"loss: {loss:.4f}", True)
            loss_summary['length'].append(length)
            loss_summary['epoch'].append(epoch + 1)
            loss_summary['loss'].append(loss)

    def _log_training_summary(self, loss_summary, path):
        if path is not None:
            try:
                PathBuilder.build(path)
                self.loss_summary_path = path / 'loss_summary.csv'
                pd.DataFrame(loss_summary).to_csv(str(self.loss_summary_path), index=False)
            except Exception as e:
                logging.error(f"{SakaLSTM.__name__}: failed to save loss summary: {e};\n{loss_summary}")

    def _export_dataset(self, sequences, path):
        count = len(sequences)
        df = pd.DataFrame({get_sequence_field_name(self.region_type, self.sequence_type): sequences,
                           'locus': [self.locus.to_string() for _ in range(count)],
                           'gen_model_name': [self.name for _ in range(count)]})

        return SequenceDataset.build_from_partial_df(df, PathBuilder.build(path), 'synthetic_saka_lstm_dataset',
                                                     {'gen_model_name': [self.name]}, {'gen_model_name': str})

    def save_model(self, path: Path) -> Path:
        model_path = PathBuilder.build(path / 'model')

        skip_keys_for_export = ['_model', '_models', 'length_probs', 'loss_summary_path', 'index_to_letter',
                                'letter_to_index', 'unique_letters', 'num_letters', 'start_index']
        write_yaml(filename=model_path / 'model_overview.yaml',
                   yaml_dict={**{k: v for k, v in vars(self).items() if k not in skip_keys_for_export},
                              **{'type': self.__class__.__name__, 'region_type': self.region_type.name,
                                 'sequence_type': self.sequence_type.name, 'locus': self.locus.name}})

        write_yaml(filename=model_path / 'length_probabilities.yaml',
                   yaml_dict={int(length): float(prob) for length, prob in self.length_probs.items()})

        for length, model in self._models.items():
            store_weights(model, model_path / f'state_dict_len_{length}.yaml')

        return Path(shutil.make_archive(str(path / f'trained_model_{self.name}'), 'zip', str(model_path))).absolute()
