import shutil
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd

from immuneML.data_model.SequenceParams import RegionType, Chain
from immuneML.data_model.bnp_util import write_yaml, read_yaml, get_sequence_field_name
from immuneML.data_model.datasets.Dataset import Dataset
from immuneML.data_model.datasets.ElementDataset import SequenceDataset
from immuneML.environment.EnvironmentSettings import EnvironmentSettings
from immuneML.environment.SequenceType import SequenceType
from immuneML.ml_methods.generative_models.GenerativeModel import GenerativeModel
from immuneML.ml_methods.generative_models.OLGA import OLGA
from immuneML.util.Logger import print_log
from immuneML.util.ParameterValidator import ParameterValidator
from immuneML.util.PathBuilder import PathBuilder


class TCRsep(GenerativeModel):
    """
    TCRsep is a selection model for human T-cell receptor beta chain repertoires. It models the probability of a
    clonotype (CDR3 amino acid sequence with V and J gene) as ``P_post = P_gen * Q``, where P_gen is given by an OLGA
    model and the selection factor Q is predicted by a neural network from TCR2vec and CDR3vec embeddings. The network
    is trained to separate the training repertoire from sequences sampled from the OLGA model. New sequences are
    generated by rejection sampling: sequences are sampled from the OLGA model and kept with probability
    min(Q, sampling_bound) / sampling_bound, so about sampling_bound sequences are sampled, reconstructed and embedded
    per generated sequence, which makes generation slower than for most other generative models. The reported p_gen is
    the post-selection probability P_gen * Q. It is a wrapper around the tcrsep package
    (https://github.com/deepomicslab/TCRsep), which has to be installed separately (e.g., with the gen_models extra of
    immuneML).

    Only human TRB data are supported. Before training, sequences with non-standard amino acids, longer than max_length,
    non-productive, not starting with C, or with a V or J gene not usable in the OLGA model are removed, as well as
    duplicated clonotypes. Alleles are ignored and generated sequences have V and J genes without alleles.

    Original publication:

    Jiang, Y., Zhang, S., Huo, M., & Li, S. C. (2025). Deep generative selection models of T-cell receptor
    repertoires with TCRsep. Nature Machine Intelligence, 7, 1331–1345. https://doi.org/10.1038/s42256-025-01085-9

    **Specification arguments:**

    - default_model_name (str): name of the default OLGA model; only humanTRB is supported; default humanTRB

    - custom_model_path (str): path to a custom OLGA model for human TRB; if set, used instead of default_model_name

    - tcr2vec_model_path (str): optional path to a pretrained TCR2vec model (hidden size 128) to embed the full TCRβ;
      if not set, the model shipped with the package is used

    - cdr3vec_model_path (str): optional path to a pretrained CDR3vec model to embed the CDR3; if not set, the model
      shipped with the package is used

    - n_gen_seqs (int): number of sequences to sample from the OLGA model for training; if not set, as many as there
      are training sequences

    - alpha (float): the α parameter of the α-relative L2 loss; default 0.1

    - epochs (int): maximum number of training epochs; default 500

    - batch_size (int): number of sequences in each batch; default 512

    - learning_rate (float): learning rate for the Adam optimizer; default 0.0001

    - early_stopping (bool): whether to stop training when the validation loss stops improving; default True

    - validation_ratio (float): fraction of sequences used for validation if early_stopping is True; default 0.1

    - max_length (int): training sequences with longer CDR3 amino acid sequences are removed; default 30

    - require_c_start (bool): if True, training sequences that do not start with C are removed; default True

    - allow_family_calls (bool): if True, V and J gene calls resolved only to the gene family (e.g., TRBV20) are kept;
      default False

    - sampling_bound (float): the rejection sampling bound; sequences with larger Q are undersampled, while larger
      values make generation slower; default 10

    - device (str): torch device to use, e.g., cpu or cuda:0; default cpu

    - num_processes (int): number of processes to use for sampling and computing P_gen; default 1

    - seed (int): random seed for the model or None

    **YAML specification:**

    .. indent with spaces
    .. code-block:: yaml

        definitions:
            ml_methods:
                my_tcrsep:
                    TCRsep:
                        default_model_name: humanTRB
                        n_gen_seqs: 100000
                        alpha: 0.1
                        epochs: 500
                        batch_size: 512
                        learning_rate: 0.0001
                        early_stopping: True
                        validation_ratio: 0.1
                        device: cpu
                        num_processes: 4
                        seed: 1

    """

    STATE_DICT_FILE_NAME = 'tcrsep.pth'
    OLGA_MODEL_FOLDER = 'olga_model'
    EMBEDDING_MODEL_FOLDER = 'embedding_model'
    EMBEDDING_MODEL_NAMES = ['TCR2vec', 'CDR3vec']
    EMBEDDING_MODEL_FILES = ['config.json', 'pytorch_model.bin']
    EMBEDDING_SIZE = 128  # input size of each branch of the package's selection network
    SUPPORTED_DEFAULT_MODELS = ['humanTRB']
    MIN_TRAINING_ITERATIONS = 200  # the package checks the initialization after 200 iterations

    @classmethod
    def load_model(cls, path: Path):
        import torch

        assert path.exists(), f"{cls.__name__}: {path} does not exist."
        for file in [path / 'model_overview.yaml', path / cls.STATE_DICT_FILE_NAME]:
            assert file.exists(), f"{cls.__name__}: {file} is not a file."

        model_overview = read_yaml(path / 'model_overview.yaml')
        z = float(model_overview.pop('Z'))
        params = {k: v for k, v in model_overview.items() if k != 'type'}

        # the OLGA model stored with the trained model is used, so the original custom_model_path does not have to exist
        # the OLGA and custom embedding models stored with the trained model are used, so the original paths do not
        # have to exist
        stored_paths = {'custom_model_path': path / cls.OLGA_MODEL_FOLDER}
        for name, param in zip(cls.EMBEDDING_MODEL_NAMES, ['tcr2vec_model_path', 'cdr3vec_model_path']):
            if params.get(param) is not None:
                stored_paths[param] = path / cls.EMBEDDING_MODEL_FOLDER / name
        model = TCRsep(**{**params, **{k: str(v) for k, v in stored_paths.items()}})
        for param in stored_paths:
            setattr(model, param, params.get(param))

        model._tcrsep = model._make_upstream_model()
        model._tcrsep.model.load_state_dict(torch.load(path / cls.STATE_DICT_FILE_NAME, map_location=model.device))
        model._tcrsep.model.eval()
        model._tcrsep.Z = z
        return model

    def __init__(self, default_model_name: str = 'humanTRB', custom_model_path: str = None,
                 tcr2vec_model_path: str = None, cdr3vec_model_path: str = None, n_gen_seqs: int = None,
                 alpha: float = 0.1, epochs: int = 500, batch_size: int = 512, learning_rate: float = 0.0001,
                 early_stopping: bool = True, validation_ratio: float = 0.1, max_length: int = 30,
                 require_c_start: bool = True, allow_family_calls: bool = False, sampling_bound: float = 10.,
                 device: str = 'cpu', num_processes: int = 1, name: str = None, seed: int = None):
        super().__init__(locus=Chain.BETA, name=name, region_type=RegionType.IMGT_JUNCTION, seed=seed)
        location = TCRsep.__name__

        for param_name, value in [('epochs', epochs), ('batch_size', batch_size), ('max_length', max_length),
                                  ('num_processes', num_processes)]:
            ParameterValidator.assert_type_and_value(value, int, location, param_name, min_inclusive=1)
        ParameterValidator.assert_type_and_value(n_gen_seqs, int, location, 'n_gen_seqs', min_inclusive=1,
                                                 nullable=True)
        ParameterValidator.assert_type_and_value(alpha, (int, float), location, 'alpha', min_exclusive=0,
                                                 max_exclusive=1)
        ParameterValidator.assert_type_and_value(learning_rate, (int, float), location, 'learning_rate',
                                                 min_exclusive=0)
        ParameterValidator.assert_type_and_value(validation_ratio, (int, float), location, 'validation_ratio',
                                                 min_inclusive=0, max_exclusive=1)
        ParameterValidator.assert_type_and_value(sampling_bound, (int, float), location, 'sampling_bound',
                                                 min_exclusive=0)
        ParameterValidator.assert_type_and_value(early_stopping, bool, location, 'early_stopping')
        ParameterValidator.assert_type_and_value(require_c_start, bool, location, 'require_c_start')
        ParameterValidator.assert_type_and_value(allow_family_calls, bool, location, 'allow_family_calls')
        assert not early_stopping or validation_ratio > 0, \
            f"{location}: validation_ratio has to be larger than 0 when early_stopping is True."
        ParameterValidator.assert_type_and_value(device, str, location, 'device')

        self.default_model_name = default_model_name
        self.custom_model_path = custom_model_path
        self.tcr2vec_model_path = tcr2vec_model_path
        self.cdr3vec_model_path = cdr3vec_model_path
        self.n_gen_seqs = n_gen_seqs
        self.alpha = alpha
        self.epochs = epochs
        self.batch_size = batch_size
        self.learning_rate = learning_rate
        self.early_stopping = early_stopping
        self.validation_ratio = validation_ratio
        self.max_length = max_length
        self.require_c_start = require_c_start
        self.allow_family_calls = allow_family_calls
        self.sampling_bound = sampling_bound
        self.device = device
        self.num_processes = num_processes

        self._olga_model_path = self._get_olga_model_path()
        self._embedding_model_paths = self._get_embedding_model_paths()
        self._alphabet = set(EnvironmentSettings.get_sequence_alphabet(SequenceType.AMINO_ACID))
        self._tcrsep = None
        self._embedding_models = None
        self._v_genes = None
        self._j_genes = None
        self._v_families = None
        self._j_families = None

    def _get_olga_model_path(self) -> Path:
        if self.custom_model_path is not None and self.custom_model_path != '':
            model_path = Path(self.custom_model_path)
            for filename in OLGA.MODEL_FILENAMES.values():
                assert (model_path / filename).is_file(), \
                    f"{TCRsep.__name__}: file {filename} is missing in the custom OLGA model folder {model_path}."
            return model_path
        else:
            from olga import load_model

            ParameterValidator.assert_in_valid_list(self.default_model_name, TCRsep.SUPPORTED_DEFAULT_MODELS,
                                                    TCRsep.__name__, 'default_model_name')
            return Path(load_model.__file__).parent / \
                f"default_models/{OLGA.DEFAULT_MODEL_FOLDER_MAP[self.default_model_name]}"

    def _get_embedding_model_paths(self) -> list:
        import json

        paths = []
        for name, param, custom_path in zip(TCRsep.EMBEDDING_MODEL_NAMES, ['tcr2vec_model_path', 'cdr3vec_model_path'],
                                            [self.tcr2vec_model_path, self.cdr3vec_model_path]):
            if custom_path is None or custom_path == '':
                import tcrsep
                paths.append(Path(tcrsep.__file__).parent / 'models/embedding_model' / name)
                continue

            ParameterValidator.assert_type_and_value(custom_path, str, TCRsep.__name__, param)
            model_path = Path(custom_path)
            for filename in TCRsep.EMBEDDING_MODEL_FILES:
                assert (model_path / filename).is_file(), \
                    f"{TCRsep.__name__}: file {filename} is missing in the {param} folder {model_path}."
            hidden_size = json.loads((model_path / 'config.json').read_text()).get('hidden_size')
            assert hidden_size == TCRsep.EMBEDDING_SIZE, \
                f"{TCRsep.__name__}: the model in {param} ({model_path}) has hidden size {hidden_size}, but the " \
                f"selection network of the tcrsep package requires embeddings of size {TCRsep.EMBEDDING_SIZE}."
            paths.append(model_path)
        return paths

    @property
    def _sequence_field(self):
        return get_sequence_field_name(self.region_type, SequenceType.AMINO_ACID)

    @staticmethod
    def _set_seed(seed: int):
        import torch
        if seed is not None:
            np.random.seed(seed)
            torch.manual_seed(seed)

    def _make_upstream_model(self):
        from tcrsep.estimator import TCRsep as UpstreamTCRsep

        model = UpstreamTCRsep(alpha=self.alpha, device=self.device, gen_model_path=str(self._olga_model_path),
                               optimizer='adam', lr=self.learning_rate)
        model.default_gen_model.processes = self.num_processes
        genomic_data = model.default_gen_model.genomic_data
        # genes with an empty CDR3 part cannot be used by OLGA (e.g., pseudogenes without a conserved anchor)
        self._v_genes = sorted({gene[0].split('*')[0] for gene in genomic_data.genV if gene[1] != ''})
        self._j_genes = sorted({gene[0].split('*')[0] for gene in genomic_data.genJ if gene[1] != ''})
        # families with at least one usable gene, for gene calls resolved only to the family (e.g., TRBV20)
        self._v_families = sorted({gene.split('-')[0] for gene in self._v_genes if '-' in gene} - set(self._v_genes))
        self._j_families = sorted({gene.split('-')[0] for gene in self._j_genes if '-' in gene} - set(self._j_genes))
        return model

    def fit(self, data: Dataset, path: Path = None):
        self._check_locus(data)
        self._set_seed(self.seed)
        self._tcrsep = self._make_upstream_model()

        post_samples = self._filter_training_data(data.data.topandas())
        post_emb, valid = self._embed(post_samples)
        post_samples, post_emb = post_samples[valid], post_emb[valid]
        if not np.all(valid):
            print_log(f"{TCRsep.__name__}: removed {np.sum(~valid)} training sequences for which the full TCRβ "
                      f"sequence could not be reconstructed from the V gene.", True)

        n_pre = self.n_gen_seqs if self.n_gen_seqs is not None else len(post_samples)
        print_log(f"{TCRsep.__name__}: sampling {n_pre} pre-selection sequences from the generation model "
                  f"{self._olga_model_path}...", True)
        pre_samples = self._sample_from_gen_model(n_pre)
        pre_emb, valid = self._embed(pre_samples)
        pre_emb = pre_emb[valid]

        batch_size = self._get_batch_size(len(post_emb), len(pre_emb))
        print_log(f"{TCRsep.__name__}: training the selection model on {len(post_emb)} post-selection and "
                  f"{len(pre_emb)} pre-selection sequences with batch size {batch_size}...", True)

        with tempfile.TemporaryDirectory() as tmp_dir:
            checkpoint = str(Path(tmp_dir) / TCRsep.STATE_DICT_FILE_NAME) if self.early_stopping else None
            self._tcrsep.train(self.epochs, post_emb, pre_emb, batch_size=batch_size, save_checkpoint=checkpoint,
                               valid_ratio=self._validation_ratio, verbose=True)

        self._tcrsep.model.eval()
        print_log(f"{TCRsep.__name__}: finished training (normalization constant Z = {self._tcrsep.Z:.4f}).", True)

    def _check_locus(self, data: Dataset):
        loci = [locus for locus in data.get_locus() if locus not in [None, '']]
        assert all(Chain.get_chain(locus) == Chain.BETA for locus in loci), \
            f"{TCRsep.__name__}: only TRB data are supported, but the dataset has loci {loci}."

    @property
    def _validation_ratio(self) -> float:
        # the package uses early stopping if and only if part of the data is used for validation
        return self.validation_ratio if self.early_stopping else 0.

    def _get_batch_size(self, n_post: int, n_pre: int) -> int:
        n_train = [n - int(n * self._validation_ratio) for n in [n_post, n_pre]]
        if self.early_stopping:
            assert all(int(n * self.validation_ratio) > 0 for n in [n_post, n_pre]), \
                f"{TCRsep.__name__}: there are too few sequences ({n_post} post-selection, {n_pre} pre-selection) " \
                f"for validation_ratio {self.validation_ratio}."

        # the package's data loader skips the first batch of each pass, so at least two batches are needed
        batch_size = min(self.batch_size, min(n_train) // 2)
        assert batch_size >= 1, f"{TCRsep.__name__}: too few training sequences ({n_post} post-selection, " \
                                f"{n_pre} pre-selection)."

        iterations = self.epochs * (max(n_post, n_pre) // batch_size)
        if iterations <= TCRsep.MIN_TRAINING_ITERATIONS:
            raise ValueError(f"{TCRsep.__name__}: training would run for {iterations} iterations (epochs times the "
                             f"number of batches), but the tcrsep package requires more than "
                             f"{TCRsep.MIN_TRAINING_ITERATIONS}; increase epochs or n_gen_seqs, or decrease "
                             f"batch_size.")
        return batch_size

    def _filter_training_data(self, df: pd.DataFrame) -> np.ndarray:
        seq_col = self._sequence_field
        original_count = df.shape[0]
        assert 'v_call' in df.columns and 'j_call' in df.columns, \
            f"{TCRsep.__name__}: v_call and j_call are required in the training data."

        df = df[df[seq_col].notna() & df['v_call'].notna() & df['j_call'].notna()].copy()
        df[seq_col] = df[seq_col].astype(str)
        df['v_call'], df['j_call'] = self._to_gene_level(df['v_call']), self._to_gene_level(df['j_call'])

        keep = self._is_valid_sequence(df[seq_col]) & self._usable_genes(df['v_call'], df['j_call'])
        if 'productive' in df.columns:
            keep &= ~df['productive'].astype(str).str.upper().isin(['F', 'FALSE'])
        if self.require_c_start:
            keep &= df[seq_col].str.startswith('C')

        df = df[keep]
        filtered_count = df.shape[0]
        df = df.drop_duplicates(subset=[seq_col, 'v_call', 'j_call'])
        family_count = int(np.sum(df['v_call'].isin(self._v_families) | df['j_call'].isin(self._j_families)))

        print_log(f"{TCRsep.__name__}: removed {original_count - filtered_count} out of {original_count} training "
                  f"sequences (empty, longer than {self.max_length}, non-standard amino acids, non-productive"
                  f"{', not starting with C' if self.require_c_start else ''}, missing V or J gene or genes not usable "
                  f"in the generation model), and {filtered_count - df.shape[0]} duplicated clonotypes; "
                  f"{family_count} of the remaining sequences have a V or J gene call resolved only to the family.",
                  True)

        assert df.shape[0] > 0, f"{TCRsep.__name__}: no training sequences left after filtering; check that the " \
                                f"data are human TRB junctions with V and J genes in IMGT nomenclature."
        return df[[seq_col, 'v_call', 'j_call']].values.astype(str)

    def _usable_genes(self, v_calls, j_calls) -> np.ndarray:
        """returns whether the gene-level V and J calls can be used by the generation model"""
        v_usable, j_usable = self._v_genes + (self._v_families if self.allow_family_calls else []), \
            self._j_genes + (self._j_families if self.allow_family_calls else [])
        return np.asarray(pd.Series(v_calls).isin(v_usable).values & pd.Series(j_calls).isin(j_usable).values)

    @staticmethod
    def _to_gene_level(genes) -> pd.Series:
        return pd.Series(genes).astype(str).str.split('*').str[0].str.strip()

    def _is_valid_sequence(self, sequences: pd.Series) -> pd.Series:
        return sequences.apply(lambda seq: 0 < len(seq) <= self.max_length and all(aa in self._alphabet for aa in seq))

    def _sample_from_gen_model(self, count: int, with_nucleotide: bool = False) -> np.ndarray:
        """returns an array with rows [CDR3 aa, V gene, J gene] (and CDR3 nt if with_nucleotide) sampled from P_gen as
        the package's Generation_model.sample does, but without a process pool if num_processes is 1"""
        gen_model = self._tcrsep.default_gen_model
        if self.num_processes > 1:
            return gen_model.sample(count, nn_seq=with_nucleotide)
        seeds = np.random.randint(2 ** 32 - 1, size=count)
        samples = np.array([gen_model.generate(seed) for seed in seeds]).reshape(count, 4)
        return samples if with_nucleotide else samples[:, :-1]

    def _get_embedding_models(self):
        if self._embedding_models is None:
            from tcr2vec.model import TCR2vec

            self._embedding_models = [TCR2vec(str(model_path)).to(self.device).eval()
                                      for model_path in self._embedding_model_paths]
        return self._embedding_models

    def _reconstruct_full_sequences(self, samples: list) -> np.ndarray:
        import tcrsep
        from tcrsep.utils import cdr2full, _wrapper

        if self.num_processes > 1 and len(samples) > self.num_processes:
            import multiprocessing as mp
            directory = str(Path(tcrsep.__file__).parent / 'gene_segment') + '/'
            chunk_size = int(np.ceil(len(samples) / self.num_processes))
            chunks = [(directory, samples[i: i + chunk_size]) for i in range(0, len(samples), chunk_size)]
            with mp.Pool(processes=self.num_processes) as pool:
                full_seqs = np.concatenate(pool.map(_wrapper, chunks))
        else:
            full_seqs = cdr2full(samples)
        return np.array([seq.decode('utf-8') if isinstance(seq, bytes) else str(seq) for seq in full_seqs])

    def _embed(self, samples: np.ndarray) -> tuple:
        """
        returns the embeddings used as input to the selection model, as in get_embedded_data from tcrsep.utils: the
        L2-normalized mean-pooled TCR2vec embedding of the full TCRβ, concatenated with the L2-normalized CDR3vec
        embedding of the CDR3; rows for which the full TCRβ could not be reconstructed are zero and marked as invalid
        """
        import torch
        from tcrsep.dataset import TCRLabeledDset
        from tcrsep.utils import l2_norm
        from torch.utils.data import DataLoader

        embeddings = np.zeros((len(samples), 256), dtype=np.float32)
        if len(samples) == 0:
            return embeddings, np.zeros(0, dtype=bool)

        full_seqs = self._reconstruct_full_sequences([list(s[:3]) for s in samples])
        valid = full_seqs != 'Failure'
        if not np.any(valid):
            return embeddings, valid

        parts = []
        for model, seqs in zip(self._get_embedding_models(), [full_seqs[valid], samples[valid, 0]]):
            dataset = TCRLabeledDset(list(seqs), only_tcr=True)
            loader = DataLoader(dataset, batch_size=128, collate_fn=dataset.collate_fn, shuffle=False)
            emb = []
            with torch.no_grad():
                for batch in loader:
                    emb.append(model({'input_ids': batch['input_ids'].to(self.device),
                                      'input_mask': batch['input_mask'].to(self.device)}, detach=True))
            parts.append(l2_norm(np.concatenate(emb)))

        embeddings[valid] = np.concatenate(parts, axis=1)
        return embeddings, valid

    def _selection_factors(self, samples: np.ndarray) -> tuple:
        """returns Q (normalized with the package's constant Z so that E_Pgen[Q] = 1) and which samples are valid"""
        embeddings, valid = self._embed(samples)
        q = np.zeros(len(samples))
        if np.any(valid):
            q[valid] = self._tcrsep.predict_weights(embeddings[valid])
        return q, valid

    def is_same(self, model) -> bool:
        import torch

        if not isinstance(model, TCRsep) or self._export_params() != model._export_params():
            return False
        if self._tcrsep is None or model._tcrsep is None:
            return self._tcrsep is None and model._tcrsep is None

        other_state = model._tcrsep.model.state_dict()
        return self._tcrsep.Z == model._tcrsep.Z and \
            all(torch.equal(val.cpu(), other_state[key].cpu()) for key, val in self._tcrsep.model.state_dict().items())

    def generate_sequences(self, count: int, seed: int, path: Path, sequence_type: SequenceType, compute_p_gen: bool,
                           max_failed_batches: int = 100):
        if compute_p_gen and sequence_type != SequenceType.AMINO_ACID:
            raise NotImplementedError(f"{TCRsep.__name__}: p_gen can only be computed for amino acid sequences.")
        assert self._tcrsep is not None, f"{TCRsep.__name__}: the model has to be fitted or loaded before generation."

        self._set_seed(seed)
        self._tcrsep.model.eval()
        accepted, accepted_q, failed_batches, sampled_count, above_bound = [], [], 0, 0, 0

        while len(accepted) < count:
            num_left = count - len(accepted)
            # as in the package's TCRsep.sample: sample 10 times as many sequences as are still needed
            samples = self._sample_from_gen_model(min(10 * num_left, 100000), with_nucleotide=True)
            u = np.random.uniform(size=len(samples))
            q, valid = self._selection_factors(samples)
            accept = valid & (u <= q / self.sampling_bound)

            accepted.extend(samples[accept][:num_left].tolist())
            accepted_q.extend(q[accept][:num_left].tolist())
            sampled_count += len(samples)
            above_bound += int(np.sum(q > self.sampling_bound))

            if not np.any(accept):
                failed_batches += 1
                if failed_batches >= max_failed_batches:
                    raise RuntimeError(f"{TCRsep.__name__}: no sequences were accepted in {max_failed_batches} "
                                       f"batches of rejection sampling.")

        if above_bound > 0:
            print_log(f"{TCRsep.__name__}: {above_bound} out of {sampled_count} sampled sequences had a selection "
                      f"factor above sampling_bound ({self.sampling_bound}) and are undersampled.", True)

        accepted = np.array(accepted)
        df = pd.DataFrame({self._sequence_field: accepted[:, 0],
                           get_sequence_field_name(self.region_type, SequenceType.NUCLEOTIDE): accepted[:, 3],
                           'v_call': accepted[:, 1], 'j_call': accepted[:, 2]})
        if compute_p_gen:
            df['p_gen'] = self._p_gens(accepted[:, :3]) * np.array(accepted_q)

        df['locus'] = self.locus.to_string()
        df['gen_model_name'] = self.name

        print_log(f"{TCRsep.__name__} {self.name}: generated {count} sequences (accepted {count} out of "
                  f"{sampled_count} sequences sampled from the generation model).", True)

        type_dict = {'gen_model_name': str, **({'p_gen': float} if compute_p_gen else {})}
        return SequenceDataset.build_from_partial_df(df, PathBuilder.build(path), 'synthetic_tcrsep_dataset',
                                                     {'gen_model_name': [self.name]}, type_dict)

    def compute_p_gens(self, sequences, sequence_type: SequenceType, sequence_field: str = None) -> np.ndarray:
        """
        Computes the post-selection probability P_post = P_gen * Q of each clonotype (CDR3 amino acid sequence, V and J
        gene), where P_gen is normalized over productive sequences as in the tcrsep package. Sequences with non-standard
        amino acids, V or J genes not usable in the generation model, or V genes for which the full TCRβ sequence cannot
        be reconstructed get p_gen 0. Sequences can be given as a SequenceDataset, a pandas DataFrame or a bionumpy
        dataclass (e.g., AIRRSequenceSet) with v_call and j_call.
        """
        if sequence_type != SequenceType.AMINO_ACID:
            raise NotImplementedError(f"{TCRsep.__name__}: p_gen can only be computed for amino acid sequences.")
        assert self._tcrsep is not None, f"{TCRsep.__name__}: the model has to be fitted or loaded first."

        samples = self._extract_samples(sequences, sequence_field)
        p_post = np.zeros(len(samples))
        valid = np.array([len(seq) > 0 and all(aa in self._alphabet for aa in seq) for seq in samples[:, 0]],
                         dtype=bool) & self._usable_genes(samples[:, 1], samples[:, 2])

        if np.any(valid):
            q, valid_emb = self._selection_factors(samples[valid])
            p_post[np.where(valid)[0]] = np.where(valid_emb, self._p_gens(samples[valid]) * q, 0.)
        return p_post

    def compute_p_gen(self, sequence: dict, sequence_type: SequenceType, sequence_field: str = None) -> float:
        field = sequence_field if sequence_field is not None else \
            (self._sequence_field if self._sequence_field in sequence else 'sequence_aa')
        df = pd.DataFrame({field: [sequence[field]], 'v_call': [sequence['v_call']], 'j_call': [sequence['j_call']]})
        return float(self.compute_p_gens(df, sequence_type, field)[0])

    def _extract_samples(self, sequences, sequence_field: str = None) -> np.ndarray:
        if isinstance(sequences, SequenceDataset):
            sequences = sequences.data
        if isinstance(sequences, pd.DataFrame):
            columns = sequences.columns
            get_col = lambda col: sequences[col].astype(str).tolist()
        else:
            columns = [f for f in [sequence_field, self._sequence_field, 'sequence_aa', 'v_call', 'j_call']
                       if f is not None and hasattr(sequences, f)]
            get_col = lambda col: [str(s) for s in getattr(sequences, col).tolist()]

        field = sequence_field if sequence_field is not None else \
            (self._sequence_field if self._sequence_field in columns else 'sequence_aa')
        assert field in columns and 'v_call' in columns and 'j_call' in columns, \
            f"{TCRsep.__name__}: the input has to contain {field}, v_call and j_call."

        return np.array([get_col(field), self._to_gene_level(get_col('v_call')).tolist(),
                         self._to_gene_level(get_col('j_call')).tolist()], dtype=object).T.reshape(-1, 3).astype(str)

    def _p_gens(self, samples: np.ndarray) -> np.ndarray:
        """P_gen from the OLGA model on the gene level, normalized as in the package's Generation_model.p_gen"""
        gen_model = self._tcrsep.default_gen_model
        samples = [list(s) for s in samples]
        if self.num_processes > 1 and len(samples) > self.num_processes:
            import multiprocessing as mp
            chunk_size = int(np.ceil(len(samples) / self.num_processes))
            with mp.Pool(processes=self.num_processes) as pool:
                p_gens = np.concatenate(pool.map(gen_model._compute_pgen, [samples[i: i + chunk_size] for i in
                                                                           range(0, len(samples), chunk_size)]))
        else:
            p_gens = np.array(gen_model._compute_pgen(samples))
        return p_gens / gen_model.norm

    def can_compute_p_gens(self) -> bool:
        return True

    def can_generate_from_skewed_gene_models(self) -> bool:
        return False

    def generate_from_skewed_gene_models(self, v_genes: list, j_genes: list, seed: int, path: Path,
                                         sequence_type: SequenceType, batch_size: int, compute_p_gen: bool):
        raise NotImplementedError(f"{TCRsep.__name__}: generating sequences from skewed gene models is not supported.")

    def _export_params(self) -> dict:
        return {'default_model_name': self.default_model_name, 'custom_model_path': self.custom_model_path,
                'tcr2vec_model_path': self.tcr2vec_model_path, 'cdr3vec_model_path': self.cdr3vec_model_path,
                'n_gen_seqs': self.n_gen_seqs, 'alpha': self.alpha, 'epochs': self.epochs,
                'batch_size': self.batch_size, 'learning_rate': self.learning_rate,
                'early_stopping': self.early_stopping, 'validation_ratio': self.validation_ratio,
                'max_length': self.max_length, 'require_c_start': self.require_c_start,
                'allow_family_calls': self.allow_family_calls, 'sampling_bound': self.sampling_bound,
                'device': self.device, 'num_processes': self.num_processes,
                'name': self.name, 'seed': self.seed}

    def save_model(self, path: Path) -> Path:
        import torch

        model_path = PathBuilder.build(path / 'model')
        write_yaml(filename=model_path / 'model_overview.yaml',
                   yaml_dict={'type': self.__class__.__name__, **self._export_params(),
                              'Z': float(self._tcrsep.Z)})
        torch.save({k: v.cpu() for k, v in self._tcrsep.model.state_dict().items()},
                   model_path / TCRsep.STATE_DICT_FILE_NAME)

        olga_path = PathBuilder.build(model_path / TCRsep.OLGA_MODEL_FOLDER)
        for filename in OLGA.MODEL_FILENAMES.values():
            if (Path(self._olga_model_path) / filename).resolve() != (olga_path / filename).resolve():
                shutil.copy(Path(self._olga_model_path) / filename, olga_path / filename)

        # custom embedding models are stored with the model; the default ones are loaded from the tcrsep package
        for name, custom_path, source_path in zip(TCRsep.EMBEDDING_MODEL_NAMES,
                                                  [self.tcr2vec_model_path, self.cdr3vec_model_path],
                                                  self._embedding_model_paths):
            if custom_path is not None and custom_path != '':
                emb_path = PathBuilder.build(model_path / TCRsep.EMBEDDING_MODEL_FOLDER / name)
                for filename in TCRsep.EMBEDDING_MODEL_FILES:
                    if (source_path / filename).resolve() != (emb_path / filename).resolve():
                        shutil.copy(source_path / filename, emb_path / filename)

        return Path(shutil.make_archive(str(path / f'trained_model_{self.name}'), 'zip', str(model_path))).absolute()
