# -*- coding: utf-8 -*-
# Copyright (c) 2020, immuneML Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""This module just contains some info for immuneML.

Here we define the name of the program and some other
relevant info.

This file is generated by immuneML (``setup_version.py``)
"""
PROGRAM_NAME = 'immuneML'
URL = 'https://greifflab.org/software/'
GIT_URL = 'https://github.com/uio-bmi/ImmuneML'
CITE = """
[1] x. yyy, z. kkk, J. Journaly McJounralFace, 2021
    doi: https://soon.666

"""
LOGO = r"""
                                                ____   ____  ___
   ____  __  __    __  __   __  __ __  _______  \   \ /   /  \ /
   \  / /  |/  |  /  |/  | / / / /   |/ / ___/  | |\ \ /| |  | |
   / / / / | / | / / | / |/ / / / /| | / _/     | | \_/ | |  | |
  / / / /|  /| |/ /|  /| | /_/ / / |  / /___    | |     | |  | |___
 /__\/_/ |_/ |_|_/ |_/ |_|____/_/  |_/______\  /___\   /___\ /_____\

"""
