# -*- coding: utf-8 -*-
# Copyright (c) 2020, immune-ML Development Team.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""This module just contains some info for immune-ML.

Here we define the name of the program and some other
relevant info.

This file is generated by immune-ML (``setup_version.py``)
"""
PROGRAM_NAME = 'immune-ML'
URL = 'https://greifflab.org/software/'
GIT_URL = 'https://github.com/uio-bmi/immuneML_private'
CITE = """
[1] x. yyy, z. kkk, J. mc jounraly journal, 2021
    doi: https://soon.666

"""
LOGO = r"""
                                                    ____   ____  ___
   ____  __  __    __  __   __  __ __  _______      \   \ /   /  \ /
   \  / /  |/  |  /  |/  | / / / /   |/ / ___/      | |\ \ /| |  | |
   / / / / | / | / / | / |/ / / / /| | / _/    ___  | | \_/ | |  | |
  / / / /|  /| |/ /|  /| | /_/ / / |  / /___  /__/ _/ |     | |  | |___
 /__\/_/ |_/ |_|_/ |_/ |_|____/_/  |_/______\     /___\    /___\ /_____\.beta

"""
