# -*- coding: utf-8 -*-
# Copyright (c) 2020, immune-ML Development Team.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for immune-ML.

This file is generated by immune-ML (``setup_version.py``)
"""
SHORT_VERSION = '0.9.0.dev0'
VERSION = '0.9.0.dev0'
FULL_VERSION = '0.9.0.dev0'
GIT_REVISION = 'c30812a57389c370ccf24dd88f21714bf5a15d7f'
GIT_VERSION = '0.9.0.dev0+c30812a'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION

MIN_PYTHON_VERSION = (3, 7)
