# -*- coding: utf-8 -*-
# Copyright (c) 2020, immuneML Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for immuneML.

This file is generated by immuneML (``setup_version.py``)
"""
SHORT_VERSION = '1.0.1'
VERSION = '1.0.1'
FULL_VERSION = '1.0.1'
GIT_REVISION = 'ba477008ae1c2d0be62ef9c8463627a19b73c887'
GIT_VERSION = '1.0.1'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION

MIN_PYTHON_VERSION = (3, 7)
