# -*- coding: utf-8 -*-
# Copyright (c) 2020, immuneML Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for immuneML.

This file is generated by immuneML (``setup_version.py``)
"""
SHORT_VERSION = '0.9.0.dev0'
VERSION = '0.9.0.dev0'
FULL_VERSION = '0.9.0.dev0'
GIT_REVISION = 'e1db0c6cccf3ea08e825800ded014b6c360186cc'
GIT_VERSION = '0.9.0.dev0+e1db0c6'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION

MIN_PYTHON_VERSION = (3, 7)
