is_repertoire: True
paired: False
sequence_type: amino_acid
p_gen_bin_count: -1 # if used, could be 30
keep_p_gen_dist: False
remove_seqs_with_signals: True
species: human
implanting_scaling_factor: 1